#!/bin/bash

# 成都OPC中心官网 - 部署脚本
# 这个脚本会引导你完成整个部署过程

echo "🎉 欢迎使用成都OPC中心官网部署脚本"
echo "================================================"
echo ""

# 颜色定义
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# 步骤1：检查Git状态
echo -e "${BLUE}步骤 1/5: 检查Git状态${NC}"
echo "------------------------------------------------"
git status
echo ""
echo -e "${GREEN}✅ Git仓库已准备就绪${NC}"
echo ""
read -p "按Enter继续..."

# 步骤2：创建GitHub仓库
echo ""
echo -e "${BLUE}步骤 2/5: 创建GitHub仓库${NC}"
echo "------------------------------------------------"
echo "请按照以下步骤操作："
echo ""
echo "1. 打开浏览器访问: https://github.com/new"
echo "2. Repository name: chengdu-opc"
echo "3. Description: 成都OPC中心官方网站"
echo "4. Visibility: Public"
echo "5. 不要勾选任何初始化选项（README, .gitignore, license）"
echo "6. 点击 'Create repository'"
echo ""
read -p "完成后，请输入你的GitHub用户名: " GITHUB_USERNAME
echo ""

# 推送到GitHub
echo "正在推送代码到GitHub..."
git remote remove origin 2>/dev/null
git remote add origin "https://github.com/$GITHUB_USERNAME/chengdu-opc.git"
git push -u origin main

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✅ 代码已成功推送到GitHub${NC}"
    echo "仓库地址: https://github.com/$GITHUB_USERNAME/chengdu-opc"
else
    echo -e "${YELLOW}⚠️  推送失败，可能需要输入GitHub密码或token${NC}"
    echo "如果需要token，请访问: https://github.com/settings/tokens"
fi
echo ""
read -p "按Enter继续..."

# 步骤3：部署数据库到Supabase
echo ""
echo -e "${BLUE}步骤 3/5: 部署数据库到Supabase${NC}"
echo "------------------------------------------------"
echo "请按照以下步骤操作："
echo ""
echo "1. 访问: https://supabase.com"
echo "2. 点击 'Start your project'"
echo "3. 使用GitHub账号登录"
echo "4. 点击 'New project'"
echo "5. 填写信息："
echo "   - Name: chengdu-opc"
echo "   - Database Password: 设置一个强密码（记住它！）"
echo "   - Region: 选择 Northeast Asia (Tokyo)"
echo "6. 点击 'Create new project'（等待2-3分钟）"
echo ""
echo "7. 项目创建后，点击左侧 'SQL Editor'"
echo "8. 点击 'New query'"
echo "9. 复制 backend/schema.sql 的内容粘贴进去"
echo "10. 点击 'Run' 执行"
echo ""
echo "11. 点击左侧 'Settings' -> 'Database'"
echo "12. 找到 'Connection string' -> 'URI'"
echo "13. 复制连接字符串（类似: postgresql://postgres:[YOUR-PASSWORD]@...）"
echo ""
read -p "完成后，请粘贴数据库连接字符串: " DATABASE_URL
echo ""
echo -e "${GREEN}✅ 数据库连接字符串已保存${NC}"
echo ""
read -p "按Enter继续..."

# 步骤4：部署后端到Render
echo ""
echo -e "${BLUE}步骤 4/5: 部署后端到Render${NC}"
echo "------------------------------------------------"
echo "请按照以下步骤操作："
echo ""
echo "1. 访问: https://render.com"
echo "2. 点击 'Get Started' 或 'Sign Up'"
echo "3. 使用GitHub账号登录"
echo "4. 点击 'New +' -> 'Web Service'"
echo "5. 选择 'Build and deploy from a Git repository'"
echo "6. 点击 'Connect' 连接你的GitHub账号"
echo "7. 找到 'chengdu-opc' 仓库，点击 'Connect'"
echo ""
echo "8. 填写配置："
echo "   - Name: chengdu-opc-backend"
echo "   - Region: Singapore"
echo "   - Branch: main"
echo "   - Root Directory: backend"
echo "   - Runtime: Node"
echo "   - Build Command: npm install"
echo "   - Start Command: npm start"
echo "   - Instance Type: Free"
echo ""
echo "9. 点击 'Advanced' -> 'Add Environment Variable'"
echo "10. 添加以下环境变量："
echo "    - DATABASE_URL = $DATABASE_URL"
echo "    - JWT_SECRET = $(openssl rand -base64 32)"
echo "    - PORT = 10000"
echo ""
echo "11. 点击 'Create Web Service'"
echo "12. 等待部署完成（5-10分钟）"
echo "13. 复制后端URL（类似: https://chengdu-opc-backend.onrender.com）"
echo ""
read -p "完成后，请粘贴后端URL: " BACKEND_URL
echo ""
echo -e "${GREEN}✅ 后端URL已保存${NC}"
echo ""
read -p "按Enter继续..."

# 步骤5：部署前端到Vercel
echo ""
echo -e "${BLUE}步骤 5/5: 部署前端到Vercel${NC}"
echo "------------------------------------------------"
echo "请按照以下步骤操作："
echo ""
echo "1. 访问: https://vercel.com"
echo "2. 点击 'Sign Up' 或 'Login'"
echo "3. 使用GitHub账号登录"
echo "4. 点击 'Add New...' -> 'Project'"
echo "5. 找到 'chengdu-opc' 仓库，点击 'Import'"
echo ""
echo "6. 填写配置："
echo "   - Framework Preset: Vite"
echo "   - Root Directory: frontend"
echo "   - Build Command: npm run build"
echo "   - Output Directory: dist"
echo ""
echo "7. 点击 'Environment Variables'"
echo "8. 添加环境变量："
echo "    - Name: VITE_API_URL"
echo "    - Value: $BACKEND_URL"
echo ""
echo "9. 点击 'Deploy'"
echo "10. 等待部署完成（2-3分钟）"
echo "11. 复制前端URL（类似: https://chengdu-opc.vercel.app）"
echo ""
read -p "完成后，请粘贴前端URL: " FRONTEND_URL
echo ""

# 步骤6：更新后端CORS配置
echo ""
echo -e "${BLUE}额外步骤: 更新后端CORS配置${NC}"
echo "------------------------------------------------"
echo "1. 返回Render后端项目页面"
echo "2. 点击 'Environment'"
echo "3. 点击 'Add Environment Variable'"
echo "4. 添加："
echo "   - Key: FRONTEND_URL"
echo "   - Value: $FRONTEND_URL"
echo "5. 点击 'Save Changes'"
echo "6. 等待后端自动重新部署（2-3分钟）"
echo ""
read -p "完成后按Enter继续..."

# 完成
echo ""
echo "================================================"
echo -e "${GREEN}🎉 部署完成！${NC}"
echo "================================================"
echo ""
echo "你的网站已经上线了！"
echo ""
echo -e "${GREEN}前端地址:${NC} $FRONTEND_URL"
echo -e "${GREEN}后端地址:${NC} $BACKEND_URL"
echo ""
echo "接下来的步骤："
echo "1. 访问前端网站测试功能"
echo "2. 使用管理员账号登录后台（默认密码在文档中）"
echo "3. 在后台生成访问码"
echo "4. 添加社群内容（成员、活动、项目等）"
echo ""
echo "管理员登录信息："
echo "- 用户名: admin"
echo "- 密码: admin123（请立即修改！）"
echo ""
echo "常见问题："
echo "- 后端休眠: 使用 cron-job.org 定时访问后端URL"
echo "- CORS错误: 检查环境变量FRONTEND_URL是否正确"
echo "- 数据库连接失败: 检查DATABASE_URL是否正确"
echo ""
echo "详细文档请查看项目根目录的文档文件。"
echo ""
echo -e "${GREEN}祝你使用愉快！🚀${NC}"
